.TH 花臼usu "1" "2023/2/26" "User Command"

.SH NAME
花臼usu \- 输出字符串
.SH SYNOPSIS

.B 花臼usu
[\fI\,STRING\/\fR]...
.br
.B 花臼usu
\fI\,OPTION
.br
.SH DESCRIPTION
.br
关注花臼谢谢喵！
.br
不间断输出字符串`花臼usu`，辅助入脑人士在Linux环境下全自动发癫。可自定义输出内容，全方位满足需求。啊不对，目前仅适配了Ubuntu 22.04 版本，有其他需求我不想动了....
.TP
\fB\-\-help \fR
显示帮助信息并退出

.TP
\fB\-\-version \fR 显示版本信息

.SH 谁是花臼usu

姓名：花臼usu 
.br
主页<https://space.bilibili.com/9983449>
.br
直播间<https://live.bilibili.com/8707460>
.br

粉丝牌：研臼生

.br

昵称：臼臼

.br

品种：飞鼠

.br

生日：6月29日

.br

星座：巨蟹座

.br

年龄：3岁（18岁）

.br

身高：155cm/18cm

.br

画师妈妈：@澡堂歌星 <https://space.bilibili.com/604866>

.br

模型妈妈：@Dokex-尚尚 <https://space.bilibili.com/10857187>

.br

身边的小飞鼠是：鼠熟

.br

.B ~ 喜欢的东西！~

.br

酸的、甜的、酸酸甜甜的食物

.br

照着食谱做好吃的

.br

酒精饮料

.br

躺着、睡觉、躺着睡觉

.br

不用算数的推理解谜类游戏

.br

Galgame！最喜欢妹系美少女！！最最喜欢只看着我一个人的美少女！！！

.br

恐怖电影

.br

.B ！！！讨厌 ！！！

.br

蟑螂！！以及所有虫子！！

.br

影响我睡觉的事！

.br

过敏！！

.br

.B ~ 最擅长的事 ~

.br

给兔子打麻药

.br

.B ~ 未来的目标 ~

.br

半年内：15万粉丝、50w播放的视频

.br

花臼自己参与的原创曲，一听就能火的那种

.br

3D化表演唱跳rap篮球！前滚翻！后空翻！托马斯回旋！

.br

提升画技，给自己设计一套新衣，穿着出席重要场合

.br

登上大舞台，BML，拜年祭！

.SH COPYRIGHT

Copyright (C) 2020 Free Software Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

.SH REPORTING BUGS

https://github.com/Danteusu/huajiu


.SH AUTHOR

Wirtten by 五里但丁 UID:13574027
